# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-27 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empire_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('bought_for', models.DecimalField(decimal_places=2, max_digits=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('revenue_per_minute', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('current_multiplier', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volatility', models.DecimalField(decimal_places=2, max_digits=20)),
                ('growth_rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='net_worth',
            field=models.DecimalField(decimal_places=2, default=1100.0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='Empire_App.Market'),
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='Empire_App.User'),
        ),
        migrations.AddField(
            model_name='addon',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='Empire_App.Business'),
        ),
        migrations.AddField(
            model_name='addon',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='Empire_App.Market'),
        ),
    ]
