# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-30 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empire_App', '0002_auto_20190329_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='base_value',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=20),
            preserve_default=False,
        ),
    ]
