# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-28 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empire_App', '0002_auto_20190327_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addon',
            name='business',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='market',
        ),
        migrations.RemoveField(
            model_name='business',
            name='market',
        ),
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='net_worth',
            field=models.DecimalField(decimal_places=2, default=1100.0, max_digits=20),
        ),
        migrations.DeleteModel(
            name='Addon',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Market',
        ),
    ]
