# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-27 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empire_App', '0002_auto_20190327_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
