# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-28 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empire_App', '0002_auto_20190327_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addon',
            old_name='multiplier',
            new_name='revenue_per_minute',
        ),
        migrations.RenameField(
            model_name='addon_type',
            old_name='multiplier',
            new_name='revenue_per_minute',
        ),
    ]
