# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-28 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empire_App', '0003_auto_20190327_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market_Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_datetime', models.DateTimeField(auto_now=True)),
                ('shapshot_multiplier', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='Empire_App.Market')),
            ],
        ),
    ]
