# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-30 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empire_App', '0003_business_base_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_number', models.IntegerField(default=1)),
                ('snapshot_datetime', models.CharField(max_length=255)),
                ('snapshot_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('snapshot_net_worth', models.DecimalField(decimal_places=2, max_digits=20)),
                ('snapshot_num_businesses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='Empire_App.User')),
            ],
        ),
    ]
