# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-28 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empire_App', '0004_auto_20190327_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon_type',
            name='description',
            field=models.TextField(default='Addon Type Description'),
            preserve_default=False,
        ),
    ]
