# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-28 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empire_App', '0004_market_snapshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market_snapshot',
            old_name='shapshot_multiplier',
            new_name='snapshot_multiplier',
        ),
    ]
