# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-28 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empire_App', '0005_auto_20190328_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='color',
            field=models.CharField(default='black', max_length=255),
        ),
    ]
