# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-29 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empire_App', '0006_market_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='current_multiplier',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
        ),
    ]
