# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-29 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empire_App', '0007_auto_20190328_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_snapshot',
            name='snapshot_number',
            field=models.IntegerField(default=1),
        ),
    ]
